"use client";
import Image from 'next/image';
import React from 'react';
import SidebarMenuRight from './SidebarMenuR'; // Ensure the path is correct

export default function FlowAI() {
  return (
    <div className="flex min-h-screen">
      <main className="flex-1 mx-4 p-4"> {/* Main content */}
        {/* Hero Section */}
        <section id="home" className="p-8 bg-transparent mt-20">
          <div className="max-w-5xl mx-auto">
            <h1 className="text-4xl font-bold">AI Flow Diagram</h1>
            <p className="mt-10 text-lg">
            The AI Flow Diagram feature in Agatha AI allows you to create flow diagrams based on your wishes which will then be generated by AI. 
            This feature makes it easy for you to visualize complex processes or workflows quickly and efficiently.     
            </p>
            <img
              src="/elipse.svg"
              alt="Lingkaran Detail"
              className="absolute"
              style={{
                top: '70%',
                right: '5%',
                width: '700px',
                height: '700px',
                transform: 'translate(50%, -50%)',
                zIndex: 1,
              }}
            />
            <Image
              src="/flow1.svg"
              alt="Accessing AI Chart"
              width={900}
              height={300}
              className="mt-9"
            />
          </div>
        </section>

        {/* Guide Section */}
        <section className="p-8 bg-transparent mt-2"> {/* Adjust margin-top for closer positioning */}
          <div className="max-w-5xl mx-auto">
            <h2 className="text-4xl font-bold">Guide to Using the AI Flow Diagram Feature in Agatha</h2>
            <img
              src="/elipse2.svg"
              alt="Lingkaran Detail"
              className="absolute"
              style={{
                top: '150%',
                right: '91%',
                width: '700px',
                height: '700px',
                transform: 'translate(50%, -50%)',
                zIndex: 0,
              }}
            />

            {/* Feature Section */}
            <div id="access" className="mt-4 space-y-6"> {/* Adjust spacing as needed */}
              <div className="p-6 rounded-lg bg-transparent">
                <ul className="list-disc pl-6 text-2xl font-bold">
                  <li>Accessing the AI Flow Diagram Feature</li>
                </ul>
                <ol className="list-decimal pl-10 mt-5 text-lg list-item-bold">
                  <li><strong>Open Website: </strong> Access the Agatha Ai website through your browser by visiting&nbsp; 
                    <a
                      href="https://agatha-ai-vercel.app" 
                      target="_blank" 
                      rel="noopener noreferrer"
                      className="text-blue-500 hover:underline"
                    >
                      https://agatha-ai-vercel.app
                    </a>.
                  </li>
                  <li><strong>Login to Your Account: </strong> If you are not logged in, click the Login button in the top right corner of the page, and enter your credentials.</li>
                  <li><strong>Navigate to Ai Flow Diagram: </strong> On the home page, look for the AI Flow Diagram menu or icon in the navigation or dashboard.</li>
                </ol>
                <Image
                  src="/flow2.svg"
                  alt="Accessing AI Chart"
                  width={850}
                  height={300}
                  className="mt-4"
                />
              </div>

              <div id="feature" className="p-6 rounded-lg bg-transparent">
                <ul className="list-disc pl-6 text-2xl font-bold">
                  <li>How to Use the AI Flow Diagram Feature</li>
                </ul>
                <img
                src="/elipse.svg"
                alt="Lingkaran Detail"
                className="absolute"
                style={{
                    top: '280%',
                    right: '5%',
                    width: '700px',
                    height: '700px',
                    transform: 'translate(50%, -50%)',
                    zIndex: 1,
                }}
                />
                <ol className="list-decimal pl-10 mt-5 text-lg list-item-bold">
                    <li><strong>Start Creating a Diagram: </strong>After entering the AI Flow Diagram page, you will see an empty workspace and a text box to enter commands.</li>
                    <li><strong>Start Adding Flow: </strong>click the &apos;+&apos; button on the top left of the empty workspace, and select the flow as needed.</li>
                    <li><strong>Run the Created Flow: </strong>Click the &apos;Run&apos; button on the top right. Then the Chat Assistant will appear to help you.</li>
                    <li><strong>Save the Project: </strong>After creating the flow, to save it, click the save button, next to the &apos;Run&apos; button. Then the project will be saved.</li>
                    <li><strong>View Uploaded Documents: </strong>Click the button with the &apos;Table&apos; icon to view the uploaded documents.</li>
                    <li><strong>Create a New Project: </strong>Click the &apos;New File&apos; button next to the Table icon, to create a new project.</li>
                </ol>
                </div>
                
              <div id="explanation" className="p-6 rounded-lg bg-transparent">
              <ul className="list-disc pl-6 text-2xl font-bold">
                  <li>Flow Explanation in AI Flow Diagram</li>
                </ul>
              </div>
              <Image
                src="/flow3.svg"
                alt="Accessing AI Chart"
                width={850}
                height={300}
                className="mt-1 py-0 p-5"
                />
                <p  className="text-lg mt-5 p-5">To set a prompt, you can click the button next to &apos;New Chat&apos;, then select &apos;Add New Prompt&apos;. And then set the prompt.</p>
                <ol className="list-decimal pl-10 mt-5 text-lg list-item-bold">
                  <li><strong>Assistant Name: </strong>Create a name to the AI in the call.</li>
                  <li><strong>First Message: </strong>Create a message or word for AI to answer when the caller picks up</li>
                  <li><strong>Voice: </strong>Choose what kind of voice intonation they want, there are seven different intonations and voice styles.</li>
                  <li><strong>Model: </strong>To select the machine model he wants to use</li>
                  <li><strong>Temperature: </strong>Measuring AI awareness, the higher the number the more random the answers generated</li>
                  <li><strong>End Call Message: </strong>Create a closing message after finishing communicating with the caller.</li>
                  <li><strong>Number Setting: </strong>In this section you can add the name and contact number you want to contact</li>
                  <li><strong>Call: </strong>Run a call</li>
                  <li><strong>History Call: </strong>Display call history.</li>
                </ol>


              <div id="number" className="p-6 rounded-lg bg-transparent">
              <Image
                src="/phone4.svg"
                alt="Accessing AI Chart"
                width={850}
                height={300}
                className="mt-4"
                />
                <p  className="text-lg mt-5"><strong className="text-xl">AI Phone Number Call: </strong>In this menu, users can set prompts and messages that the AI will then use to call the intended number.</p>
                <ol className="list-decimal pl-10 mt-5 text-lg list-item-bold">
                  <li><strong>Start: </strong>Start the flow diagram.</li>
                  <li><strong>LLM: </strong>LLM is a machine learning model that can understand users. There are 2 machines with custom prompt and by knowledge.</li>
                  <li><strong>Knowledge Retrival: </strong>This flow provides knowledge to AI with the sources we provide in the form of files (PDF, CSV, or DOC).</li>
                  <li><strong>Vapi: </strong>Flow to add AI Telphone, where you can fill in the message and prompt as desired.</li>
                  <li><strong>End: </strong>End the flow diagram.</li>
                </ol>
                </div>

              <div id="usage-tips" className="p-6 rounded-lg bg-transparent">
                <ul className="list-disc pl-6 text-2xl font-bold">
                  <li>Usage Tips</li>
                </ul>
                <ul className="list-decimal list-item-bold pl-10 mt-5 text-lg">
                  <li><strong>Prompt Clarity: </strong>Make sure you provide a clear and specific prompt before starting the call to get optimal results.</li>
                  <li><strong>Natural Conversation: </strong>While the AI can respond well, try to speak clearly and slowly so that the AI can process and respond correctly.</li>
                </ul>
                <img
                src="/elipse2.svg"
                alt="Lingkaran Detail"
                className="absolute"
                style={{
                    top: '400%',
                    right: '91%',
                    width: '700px',
                    height: '700px',
                    transform: 'translate(50%, -50%)',
                    zIndex: 1,
                }}
                />
              </div>
            </div>
          </div>
        </section>
      </main>
      <SidebarMenuRight />  {/* Right sidebar */}
    </div>
  );
}
